version: "3"

tasks:
  gen:
    desc: Generate protobuf stubs
    sources:
      - cache.proto
    generates:
      - cache_pb2.py
      - cache_pb2_grpc.py
      - cache_pb2.pyi
    cmds:
      - uv run python -m grpc_tools.protoc -I. --python_out=. --pyi_out=. --grpc_python_out=. cache.proto

  clean:
    desc: Remove generated protobuf stubs
    cmds:
      - python -c "import os; [os.remove(p) for p in ('cache_pb2.py','cache_pb2_grpc.py','cache_pb2.pyi') if os.path.exists(p)]"

  test:
    desc: Run unit + integration tests
    deps: [gen]
    cmds:
      - uv run pytest

  format:
    desc: Auto-format code (ruff)
    cmds:
      - uv run ruff format .

  lint:
    desc: Lint code (ruff)
    cmds:
      - uv run ruff check .

  typecheck:
    desc: Typecheck code (basedpyright)
    deps: [gen]
    cmds:
      - uv run basedpyright
