version: "3"

tasks:
  gen:
    desc: Generate protobuf stubs
    sources:
      - cache.proto
    generates:
      - cache_pb2.py
      - cache_pb2_grpc.py
    cmds:
      - python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. cache.proto

  clean:
    desc: Remove generated protobuf stubs
    cmds:
      - python -c "import os; [os.remove(p) for p in ('cache_pb2.py','cache_pb2_grpc.py') if os.path.exists(p)]"

  test:
    desc: Run unit + integration tests
    deps: [gen]
    cmds:
      - python -m pytest

